version: 0.2
env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Istalling source NPM dependencies...
      - aws --version
      - npm cache clean --force      
      - npm install -g @angular/cli@latest
      - npm install
      - ng add @angular/material      
  build:
    commands:
      - echo Build started on 'date'
      - ng build  
artifacts:
  files:
    - '**/*'
  base-directory: './dist*'
  discard-paths: yes
  