# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  variable:
    APP_NAME: "community-events-front"
    S3_BUCKET: s3://fabiopinhodev.com.br
phases:
  install:
    runtime-versions:
      nodejs: 14.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`      
      - npm build      
  post_build:
    commands:
      - echo Clearing S3 bucket...
      - aws s3 rm s3://${S3_BUCKET} --recursive
      - echo Copying files to S3...
      - aws s3 cp dist/${APP_NAME} s3://${S3_BUCKET} 
  artifacts:
    files:
      - '**/*'
    discard-paths: no
    base-directory: 'dist/${APP_NAME}/browser'